events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 80;

        location /assets/ {
            root /usr/share/nginx/dashboard;
        }

        location /dashboard {
            root /usr/share/nginx;
            index index.html;
            try_files $uri $uri/ /dashboard/index.html;
        }

        location / {
            proxy_pass http://proxima:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}